---
kind: pipeline
name: default
type: docker

steps:
- name: docker
  image: plugins/docker
  settings:
    repo: yavook/kiwi-nginx-gen
    auto_tag: true
    username:
      from_secret: DOCKER_USERNAME
    password:
      from_secret: DOCKER_PASSWORD
